version: '3'


services:
    postgres-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: Password12!
        ports:
            - 8081:5432
    mysql-db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: testytest
        ports:
            - 8082:3306
   firebird-db:
        image: jacobalberty/firebird
        restart: always
        environment:
            ISC_PASSWORD: masterkey
            FIREBIRD_USER: docker
            FIREBIRD_PASSWORD: testytest
        ports:
            - 8083:3050
    adminer:
        image: jeern/adminer
        restart: always
        ports:
            - 7070:80