version: '3'

services:
    postgres-db:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: docker
            POSTGRES_PASSWORD: Password12!
        ports:
            - 8081:5432
    mysql-db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: testytest
        ports:
            - 8082:3306
    firebird-db:
        image: jacobalberty/firebird
        restart: always
        environment:
            FIREBIRD_DATABASE: test.fdb
            ISC_PASSWORD: masterkey
            FIREBIRD_USER: docker
            FIREBIRD_PASSWORD: testytest
            EnableLegacyClientAuth: 'true'
        ports:
            - 3050:3050
    oracle:
        image: sath89/oracle-12c
        restart: always
        ports:
            - 8080:8080
            - 1521:1521
    adminer:
        image: jeern/adminer:v1
        restart: always
        ports:
            - 8083:80
